# Generated by Django 4.0.4 on 2022-05-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('createur', models.CharField(max_length=100)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('utilite', models.TextField(blank=True, null=True)),
                ('lieu_creation', models.CharField(max_length=100)),
                ('nb_utilisateurs', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
