# Generated by Django 4.0.4 on 2022-05-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0002_alter_reseaux_utilite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('nom_rs', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('nationnalite', models.CharField(max_length=100)),
                ('plus', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='reseaux',
            old_name='nom',
            new_name='nom_rs',
        ),
    ]
